[package]
name = "grit"
version = "0.1.0"
edition = "2021"
description = "Brainrot git"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
configparser = "3.1.0"
flate2 = "1.1.0"
ini = "1.3.0"
